### ISSUE TITLE
undefined method `image_url' for #bust_struct

### ISSUE THREAD

**Issue by vuongngo** [Yelp/yelp-ruby#23]
Hi, 

I have a problem with undefined method while trying to fetch data. It seems that those errors occur when some elements in can not be retrieved from Yelp API (eg: missing business image). The problem is temporarily fixed in my local machine when I commended out the line 17 in bust_struct file in Yelp gem. However, when I deploy my app on Heroku, I have the same error.
I'm wondering is there anyway to fix the problem permanently?

Cheers,
Vuong

**Comment by mittonk** [comment]
"Ugly but reliable" may be better than what we've got, @tomelm 's solution seems like an improvement.

**Comment by tomelm** [comment]
This should be fixed now! It's deployed in 2.1.0
