### ISSUE TITLE
Getting one or more parameters are invalid error in request

### ISSUE THREAD

**Issue by meinac** [Yelp/yelp-ruby#28]
I've completely set configuration but when I want to make a request either business or search endpoint it throws "One or more parameters are invalid in request" error. 
Here is the result body of faraday http request;
```
{"error": {"text": "One or more parameters are invalid in request", "id": "INVALID_PARAMETER", "field": "oauth_token"}}
```

**Comment by tomelm** [comment]
Can you show me how you're adding your oauth_tokens?

**Comment by meinac** [comment]
sorry it was my fault, somehow i set wrong token and token_secret values. I'm closing this one.
