### ISSUE TITLE
Cannot retrieve business rating_img_url

### ISSUE THREAD

**Issue by butyouyes** [Yelp/yelp-ruby#42]
Try the following:
```ruby
response = client.business('yelp-san-francisco')
business = response.business
business.rating_img_url
```
returns the following error:
```ruby
NoMethodError: undefined method `rating_img_url' for #<Yelp::Response::Model::Business:0x007f9fd9859eb0>
```
While other instance variables work fine, e.g.:
```ruby
business.name
 => "Yelp"
```

There is one workaround and that is using:
```ruby
business.instance_variable_get(:@rating_img_url)
 => "http://s3-media4.fl.yelpcdn.com/assets/2/www/img/c7fb9aff59f9/ico/stars/v1/stars_2_half.png"
```

Rails v4.1.6
ruby 2.1.6p336
yelp gem 2.10

**Comment by mittonk** [comment]
This sounds a lot like #41 .

**Comment by butyouyes** [comment]
Any idea on when this will be fixed?

**Comment by tomelm** [comment]
@butyouyes this is on me, sorry I've been slow. I'm going to try to do it by the end of this week

**Comment by tomelm** [comment]
@butyouyes fixed and pushed!
