### ISSUE TITLE
"Invalid Signature" Error/Credentials not attached to URL

### ISSUE THREAD

**Issue by rachaellynn** [Yelp/yelp-ruby#43]
My gem will create a client but won't attach credentials to the URL. I get an "invalid signature" error as a result and can't figure out why. Here's some detail:

![screen shot 2015-11-30 at 12 08 49 pm](https://cloud.githubusercontent.com/assets/10420618/11478622/20a1192c-975c-11e5-9657-da68a68e1d88.png)

Thanks in advance for any help.

**Comment by tomelm** [comment]
Hey @rachaellynn! How are you setting up your client?

**Comment by rachaellynn** [comment]
hi @tomelm -- many apologies! i checked in with a colleague who ran the api successfully with your gem and it was an issue with my keys. sorry to have jumped the gun on this one. take care.
