### ISSUE TITLE
Get URLs in responses over https rather than http

### ISSUE THREAD

**Issue by butyouyes** [Yelp/yelp-ruby#46]
I am not sure if it is an issue or rather not clear from the documentation. How do you get the urls in the business data in the response to be over https rather than http? From the code I understand the request is done over https, but the values in the response (e.g. @url,@rating_image_url, etc.) are over http.
Or do I have to configure something? I have followed the standard configuration as in the documentation.

Sorry if not an issue, but rather a question.

**Comment by tomelm** [comment]
We don't have an option for that on the API itself, all the urls we do return should work with https but the API doesn't return them. Let me look into this.

**Comment by tomelm** [comment]
Hey @butyouyes, I don't really have any more information here or an ETA on this :(

**Comment by butyouyes** [comment]
In reading the API I do see that it sends only http versions.

No problem, I will update my code to change the protocol.

It does work.

Thank you for the follow up!

Andrea

**Comment by mittonk** [comment]
(We're in the process of switching return values to HTTPS).

**Comment by tomelm** [comment]
This is done, all the urls returned from v2 should be https!
