### ISSUE TITLE
Exceeded request limit error doesn't match class name

### ISSUE THREAD

**Issue by ldrbrandon** [Yelp/yelp-ruby#47]
I noticed the error is returning as a different name than what is set in error.rb

in error.rb: "class ExceededReqs < Base; end"

the error I got when I exceeded the request limit is as follows:
"uninitialized constant Yelp::Error::ExceededReqs"

I'm assuming the class name just needs to be changed? Not actually sure how to write a "good" test for this though.

**Comment by erikgrueter1** [comment]
@ldrbrandon Hey there - what is the status of this? I can't find the `ExceededReqs` constant in the project. Has this been fixed?

**Comment by ldrbrandon** [comment]
It's a class in error.rb

**Comment by tomelm** [comment]
I never deployed this, my bad. Let me get that figured out

**Comment by erikgrueter1** [comment]
@tomelm Thanks!

**Comment by erikgrueter1** [comment]
Hey @tomelm - when do you anticipate releasing this?

**Comment by tomelm** [comment]
This morning, needed to get another branch merged in. Will update soon

**Comment by tomelm** [comment]
@ldrbrandon actually, now. I pushed out 2.1.2 and it's up: https://rubygems.org/gems/yelp

Let me know if you all have any problems! Closing this for now

**Comment by erikgrueter1** [comment]
@tomelm Thanks!
