### ISSUE TITLE
Getting "description" and/or "restaurant website" from Yelp business API

### ISSUE THREAD

**Issue by kimmiies** [Yelp/yelp-ruby#52]
Hi there, 

We're trying to get some information from your website that we're not sure is available from the API. The two in particular are:
- the restaurant website vs the yelp url for the restaurant
- a description of the restaurant or "from the business" description vs the snippet_text (which gives us random views).

Any help or guidance would be greatly appreciated

**Comment by mittonk** [comment]
The business' own website isn't available through the API.

The "About This Business" text written by the business owner also isn't available.  (The `snippet_text` is drawn from user's reviews of the business.)

**Comment by ajm188** [comment]
@mittonk seems like this is closeable, no?

**Comment by mittonk** [comment]
@ajm188 : I'd be inclined to treat this as an enhancement request for the API (and therefore leave it open).  I don't feel strongly.

**Comment by tomelm** [comment]
Done: https://github.com/Yelp/yelp-fusion/issues/83

Closing this one.
