### ISSUE TITLE
SSL failures?

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-ruby#56]
```
resp = Yelp.client.business('yelp-san-francisco')
puts resp.business.name
```
```
ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
```

I probably don't have the proper top-level cert installed, what's the Ruby way of doing that?

**Comment by tomelm** [comment]
It should be using OpenSSL if you have that installed. How is Ruby setup on your system?

**Comment by mittonk** [comment]
Great, I've got a very thrown-together Ruby installation borrowed from a side project.  If a normal setup works, it's probably just my setup.
